const subjectData = 
[
  {
     "subjectInitial":"DAA",
     "subjectName":"Design and Analysis Of Algorithm",
     "subjectYear": 2020,
     "subjectPattern":"2019 Credit Pattern",
     "subjectDepartment":"Computer",
     "subjectSem": 7,
     "subjectPracticalAssigments": 0,
     "subjectTheoryAssignments": 6,
     "subjectIsPractical":false,
     "subjectMiniProjects": 0,
     "subSubjects": 0,
     "subjectIsElective":false,
     "subjectElectiveChoices":[],
     "subSubjectNames":[],
     "subjectIsHonours":false,
     "utTotal": 30,
     "utPassing": 12,
     "prelimTotal": 70,
     "prelimPassing": 28
  },
  {
     "subjectInitial":"BT",
     "subjectName":"Blockchain Technology",
     "subjectYear": 2020,
     "subjectPattern":"2019 Credit Pattern",
     "subjectDepartment":"Computer",
     "subjectSem": 7,
     "subjectPracticalAssigments": 0,
     "subjectTheoryAssignments": 6,
     "subjectIsPractical":false,
     "subjectMiniProjects": 0,
     "subSubjects": 0,
     "subjectIsElective":false,
     "subjectElectiveChoices":[],
     "subSubjectNames":[],
     "subjectIsHonours":false,
     "utTotal": 30,
     "utPassing": 12,
     "prelimTotal": 70,
     "prelimPassing": 28
  },
  {
     "subjectInitial":"ML",
     "subjectName":"Machine Learning",
     "subjectYear": 2020,
     "subjectPattern":"2019 Credit Pattern",
     "subjectDepartment":"Computer",
     "subjectSem": 7,
     "subjectPracticalAssigments": 0,
     "subjectTheoryAssignments": 6,
     "subjectIsPractical":false,
     "subjectMiniProjects": 0,
     "subSubjects": 0,
     "subjectIsElective":false,
     "subjectElectiveChoices":[],
     "subSubjectNames":[],
     "subjectIsHonours":false,
     "utTotal": 30,
     "utPassing": 12,
     "prelimTotal": 70,
     "prelimPassing": 28
  },
  {
     "subjectInitial":"EL3",
     "subjectName":"Elective 3",
     "subjectYear": 2020,
     "subjectPattern":"2019 Credit Pattern",
     "subjectDepartment":"Computer",
     "subjectSem": 7,
     "subjectPracticalAssigments": 0,
     "subjectTheoryAssignments": 6,
     "subjectIsPractical":false,
     "subjectMiniProjects": 0,
     "subSubjects": 4,
     "subjectIsElective":true,
     "subjectElectiveChoices":["Pervasive Computing","Multimedia Techniques","Cyber Security And Digital Forensics" ,"Object Oriented Modeling And Design ","Digital Signal Processing"],
     "subSubjectNames":[],
     "subjectIsHonours":false,
     "utTotal": 30,
     "utPassing": 12,
     "prelimTotal": 70,
     "prelimPassing": 28
  },
  {
     "subjectInitial":"EL4",
     "subjectName":"Elective 4",
     "subjectYear": 2020,
     "subjectPattern":"2019 Credit Pattern",
     "subjectDepartment":"Computer",
     "subjectSem": 7,
     "subjectPracticalAssigments": 0,
     "subjectTheoryAssignments": 6,
     "subjectIsPractical":false,
     "subjectMiniProjects": 2,
     "subSubjects": 4,
     "subjectIsElective":true,
     "subjectElectiveChoices":["Information Retrieval", "GPU Programming And Architecture","Mobile Computing" , "Software Testing And Quality Assurance"],
     "subSubjectNames":[],
     "subjectIsHonours":false,
     "utTotal": 30,
     "utPassing": 12,
     "prelimTotal": 70,
     "prelimPassing": 28
  },
  {
     "subjectInitial":"LP3",
     "subjectName":"Labrotary Practice 3",
     "subjectYear": 2020,
     "subjectPattern":"2019 Credit Pattern",
     "subjectDepartment":"Computer",
     "subjectSem": 7,
     "subjectPracticalAssigments": 12,
     "subjectTheoryAssignments": 0,
     "subjectIsPractical":true,
     "subjectMiniProjects": 3,
     "subSubjects": 2,
     "subjectIsElective":false,
     "subjectElectiveChoices":[],
     "subSubjectNames":["Design and Analysis of Algorithms", "Machine Learning","Blockchain Technology"],
     "subjectIsHonours":false,
     "utTotal": 0,
     "utPassing": 0,
     "prelimTotal": 0,
     "prelimPassing": 0
  },
  {
     "subjectInitial":"LP4",
     "subjectName":"Labrotary Practice 4",
     "subjectYear": 2020,
     "subjectPattern":"2019 Credit Pattern",
     "subjectDepartment":"Computer",
     "subjectSem": 7,
     "subjectPracticalAssigments": 10,
     "subjectTheoryAssignments": 0,
     "subjectIsPractical":true,
     "subjectMiniProjects": 2,
     "subSubjects": 2,
     "subjectIsElective":false,
     "subjectElectiveChoices":[],
     "subSubjectNames":["EL3", "EL4"],
     "subjectIsHonours":false,
     "utTotal": 0,
     "utPassing": 0,
     "prelimTotal": 0,
     "prelimPassing": 0
  },
  {
     "subjectInitial":"PS1",
     "subjectName":"Project Stage I",
     "subjectYear": 2020,
     "subjectPattern":"2019 Credit Pattern",
     "subjectDepartment":"Computer",
     "subjectSem": 7,
     "subjectPracticalAssigments": 0,
     "subjectTheoryAssignments": 0,
     "subjectIsPractical":true,
     "subjectMiniProjects": 0,
     "subSubjects": 0,
     "subjectIsElective":false,
     "subjectElectiveChoices":[],
     "subSubjectNames":[],
     "subjectIsHonours":false,
     "utTotal": 0,
     "utPassing": 0,
     "prelimTotal": 0,
     "prelimPassing": 0
  },
  {
     "subjectInitial":"AC7",
     "subjectName":"Audit Course",
     "subjectYear": 2020,
     "subjectPattern":"2019 Credit Pattern",
     "subjectDepartment":"Computer",
     "subjectSem": 7,
     "subjectPracticalAssigments": 0,
     "subjectTheoryAssignments": 0,
     "subjectIsPractical":true,
     "subjectMiniProjects": 0,
     "subSubjects": 0,
     "subjectIsElective":false,
     "subjectElectiveChoices":[],
     "subSubjectNames":[],
     "subjectIsHonours":false,
     "utTotal": 0,
     "utPassing": 0,
     "prelimTotal": 0,
     "prelimPassing": 0
  },
  {
     "subjectInitial":"HN",
     "subjectName":"Honor",
     "subjectYear": 2020,
     "subjectPattern":"2019 Credit Pattern",
     "subjectDepartment":"Computer",
     "subjectSem": 7,
     "subjectPracticalAssigments": 0,
     "subjectTheoryAssignments": 0,
     "subjectIsPractical":true,
     "subjectMiniProjects": 0,
     "subSubjects": 4,
     "subjectIsElective":false,
     "subjectElectiveChoices":[],
     "subSubjectNames":[],
     "subjectIsHonours":true,
     "utTotal": 30,
     "utPassing": 12,
     "prelimTotal": 70,
     "prelimPassing": 28
  }
];